# Generated by Django 4.2.27 on 2025-12-21 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='gender',
            field=models.CharField(choices=[('BOYS', 'Boys'), ('GIRLS', 'Girls')], default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='result',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
