# Generated by Django 4.2.27 on 2025-12-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='gender',
            field=models.CharField(choices=[('BOYS', 'Boys'), ('GIRLS', 'Girls')], default='BOYS', max_length=10),
        ),
    ]
