# Generated by Django 4.2.27 on 2025-12-21 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meet', '0002_event_gender_registration_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='gender',
            field=models.CharField(choices=[('BOYS', 'Boys'), ('GIRLS', 'Girls')], default='BOYS', max_length=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL),
        ),
    ]
